// <auto-generated />
using System;
using CodeRefine.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeRefine.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910060216_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeRefine.Api.Models.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommitSha")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ImprovementBranch")
                        .HasColumnType("text");

                    b.Property<int?>("ImprovementPrNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ImprovementPrUrl")
                        .HasColumnType("text");

                    b.Property<int?>("PullRequestNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("QualityScoreAfter")
                        .HasColumnType("double precision");

                    b.Property<double?>("QualityScoreBefore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceBranch")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetBranch")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "StartedAt");

                    b.ToTable("AnalysisRuns");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Recommendation")
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.Patch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FindingId");

                    b.ToTable("Patches");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubRepoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("InstallationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Owner", "Name")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("FindingId");

                    b.HasIndex("PatchId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("GitHubLogin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GitHubLogin")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.VerificationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("CheckType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId", "CheckType");

                    b.ToTable("VerificationResults");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.AnalysisRun", b =>
                {
                    b.HasOne("CodeRefine.Api.Models.Repository", "Repository")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.Finding", b =>
                {
                    b.HasOne("CodeRefine.Api.Models.AnalysisRun", "AnalysisRun")
                        .WithMany("Findings")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.Patch", b =>
                {
                    b.HasOne("CodeRefine.Api.Models.Finding", "Finding")
                        .WithMany("Patches")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.Repository", b =>
                {
                    b.HasOne("CodeRefine.Api.Models.User", "User")
                        .WithMany("Repositories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.Review", b =>
                {
                    b.HasOne("CodeRefine.Api.Models.AnalysisRun", "AnalysisRun")
                        .WithMany("Reviews")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeRefine.Api.Models.Finding", "Finding")
                        .WithMany("Reviews")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CodeRefine.Api.Models.Patch", "Patch")
                        .WithMany("Reviews")
                        .HasForeignKey("PatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CodeRefine.Api.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalysisRun");

                    b.Navigation("Finding");

                    b.Navigation("Patch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.VerificationResult", b =>
                {
                    b.HasOne("CodeRefine.Api.Models.AnalysisRun", "AnalysisRun")
                        .WithMany("VerificationResults")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.AnalysisRun", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Reviews");

                    b.Navigation("VerificationResults");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.Finding", b =>
                {
                    b.Navigation("Patches");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.Patch", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.Repository", b =>
                {
                    b.Navigation("AnalysisRuns");
                });

            modelBuilder.Entity("CodeRefine.Api.Models.User", b =>
                {
                    b.Navigation("Repositories");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
