import logging
import uuid

from app.git.publisher import commit_and_push, create_github_pr
from app.workflow.state import CodeRefineState

logger = logging.getLogger(__name__)

_BRANCH_PREFIX = "coderefine/improve-pr"


def _build_pr_body(state: CodeRefineState) -> str:
    """Build a rich Markdown PR description from the workflow state."""
    findings = state.get("aggregated_findings", [])
    verification = state.get("verification_result")
    combined_diff = state.get("combined_diff", "")
    retry_count = state.get("retry_count", 0)

    verdict = verification.verdict if verification else "unknown"
    verdict_emoji = "✅" if verdict == "passed" else "⚠️"

    lines = [
        "## CodeRefine AI Improvement",
        "",
        f"> **Verification verdict**: {verdict_emoji} `{verdict}` "
        f"(after {retry_count} repair attempt(s))",
        "",
        "---",
        "",
        "### Findings addressed",
        "",
        "| # | Agent | File | Severity | Title |",
        "|---|-------|------|----------|-------|",
    ]

    for i, f in enumerate(findings, 1):
        file_name = f.file or f.file_path or "unknown"
        lines.append(
            f"| {i} | `{f.agent_type}` | `{file_name}` | {f.severity} | {f.title} |"
        )

    lines += [
        "",
        "---",
        "",
        "### Combined diff",
        "",
        "```diff",
        combined_diff or "(no diff generated)",
        "```",
        "",
        "---",
        "",
        "*This PR was automatically generated by [CodeRefine](https://github.com). "
        "Please review the changes carefully before merging.*",
    ]

    return "\n".join(lines)


def commit_and_push_node(state: CodeRefineState) -> dict:
    """LangGraph node: commit the patched workspace and push a new branch to origin."""
    repo_path = state.get("repo_path", "")
    analysis_id = state.get("analysis_id", uuid.uuid4().hex[:8])
    pr_number = state.get("pr_number")
    verdict = "unknown"
    if state.get("verification_result"):
        verdict = state["verification_result"].verdict

    # Build a descriptive branch name
    short_id = analysis_id[:8] if len(analysis_id) >= 8 else analysis_id
    if pr_number:
        branch_name = f"{_BRANCH_PREFIX}-{pr_number}-{short_id}"
    else:
        branch_name = f"{_BRANCH_PREFIX}-{short_id}"

    # Build commit message
    finding_count = len(state.get("aggregated_findings", []))
    commit_message = (
        f"chore(coderefine): AI-generated improvements [{verdict}]\n\n"
        f"Analysis ID : {analysis_id}\n"
        f"Findings    : {finding_count}\n"
        f"Verification: {verdict}\n"
    )

    try:
        commit_and_push(repo_path=repo_path, branch_name=branch_name, commit_message=commit_message)
        logger.info("Committed and pushed improvement branch '%s'", branch_name)
        return {"improvement_branch": branch_name, "status": "pushed"}
    except Exception as exc:
        logger.error("Failed to commit/push improvement branch: %s", exc)
        return {"improvement_branch": branch_name, "status": "push_failed"}


def create_pr_node(state: CodeRefineState) -> dict:
    """LangGraph node: open a GitHub PR from the improvement branch against the original base branch."""
    repo_url = state.get("repo_url", "")
    improvement_branch = state.get("improvement_branch", "")
    pr_number = state.get("pr_number")
    analysis_id = state.get("analysis_id", "")
    verdict = "unknown"
    if state.get("verification_result"):
        verdict = state["verification_result"].verdict

    # Determine the base branch to merge the improvement PR into
    # If we were analysing a specific PR, target its head branch (the original author's branch).
    # Otherwise fall back to main/master.
    base_branch = state.get("base_branch") or "main"

    # Build PR title
    verdict_tag = "✅ Verified" if verdict == "passed" else "⚠️ Needs Review"
    if pr_number:
        pr_title = f"[CodeRefine] {verdict_tag}: AI improvements for PR #{pr_number}"
    else:
        pr_title = f"[CodeRefine] {verdict_tag}: AI improvements ({analysis_id[:8]})"

    pr_body = _build_pr_body(state)

    if not repo_url:
        logger.warning("repo_url is empty — skipping GitHub PR creation")
        return {"improvement_pr_url": "", "status": "skipped_no_repo_url"}

    if not improvement_branch:
        logger.warning("improvement_branch is empty — skipping GitHub PR creation")
        return {"improvement_pr_url": "", "status": "skipped_no_branch"}

    try:
        pr_url = create_github_pr(
            repo_url=repo_url,
            head_branch=improvement_branch,
            base_branch=base_branch,
            pr_title=pr_title,
            pr_body=pr_body,
        )
        logger.info("Created improvement PR: %s", pr_url)
        return {"improvement_pr_url": pr_url, "status": "completed"}
    except Exception as exc:
        logger.error("Failed to create GitHub PR: %s", exc)
        return {"improvement_pr_url": "", "status": "pr_creation_failed"}
